### ISSUE TITLE
Not working anymore! 

### ISSUE THREAD

**Issue by lamyergeier** [basverweij/vscode-markdown-it-gridtables#19]
I installed it by copying the repository to the vscode extension folder. The extension is recognized but its commands are not working. Could you please check?

**Comment by basverweij** [comment]
Hi @anishmittal2020, thanks for letting me know! I haven't updated this extension for some while :), but I'll have a look!

**Comment by basverweij** [comment]
@anishmittal2020: could you try installing the extension using the VSIX attached below? (You have to unzip it first.) If I do that the commands and key bindings are working fine.

![image](https://user-images.githubusercontent.com/9398734/110534725-b5dc1200-811f-11eb-9886-49f28951872a.png)

[vscode-markdown-it-gridtables-0.1.0.vsix.zip](https://github.com/basverweij/vscode-markdown-it-gridtables/files/6111241/vscode-markdown-it-gridtables-0.1.0.vsix.zip)

If this is working for you I'll try to make some time and publish it properly to the Marketplace. :)

**Comment by lamyergeier** [comment]
Yes vsix works!
